### ISSUE TITLE
path not defined

### ISSUE THREAD

**Issue by DracoMilesX** [nerdydrew/Random-Pokemon-Generator#1]
Trying to set this up locally but it appears the code isn't working and checking the dev console it shows that PATH_TO_SPRITES isn't defined.

Reverting back to an older commit before define usage is working fine.

**Comment by nerdydrew** [comment]
You need to set it in the `setup.js` file at the top level directory, as it says in the readme. I updated the [sample file](https://github.com/nerdydrew/Random-Pokemon-Generator/blob/master/setup/config.js) accordingly.

**Comment by DracoMilesX** [comment]
Thanks for the info. For some reason still not working for me.
This is how it is currently setup:

/webroot/pkmnrandom
/webroot/pkmnrandom/config.js
/webroot/pkmnrandom/config.php
/webroot/pkmnrandom/sprites/animated
/webroot/pkmnrandom/sprites/animated/shiny
/webroot/pkmnrandom/etc..

Renamed file names to remove all starting zero's

(Did had to adjust index.php because of the / infront of style.css and several others)

Nginx/PHP7.0

**Comment by nerdydrew** [comment]
Heh, my bad—I was thinking PHP instead of JavaScript when I updated the sample config. I fixed it to use `const` now. When in doubt, remember you can always look at the [live site](http://randompokemon.com/config.js), which you can verify works!

**Comment by DracoMilesX** [comment]
Thank you now it is indeed working except that now ANIMATED is added in the config.js which doesn't match the rest.

**Comment by nerdydrew** [comment]
Okay, thanks again for that. It should be fixed, for real this time.

**Comment by DracoMilesX** [comment]
All working now thank you very much:)
