### ISSUE TITLE
Feature request: Hotlinking a set of parameters

### ISSUE THREAD

**Issue by mid-kid** [nerdydrew/Random-Pokemon-Generator#5]
First of all, thanks for this nice website.

In the wild (mostly on 4chan/vp/, but probably other places, too), I see many people using this site in messages like:
> https://randompokemon.com/ generate 1 pokemon
> this pokemon knocks down your door at night. how screwed are you?

(Not an exact quote but messages [follow similar formats](https://archive.nyafuu.org/vp/search/text/randompokemon.com/end/2021-04-07/))

I think it'd be nice if when pressing the "generate" button, you'd get a URL (in your address bar), that when copied and clicked by another party, will prefill the exact same parameters as the other person, allowing you to tweak them before pressing "generate".

This could be implemented as GET parameters, or a base64 string where the fields are bitpacked to keep the URL short. Anything's good.

**Comment by nerdydrew** [comment]
I just pushed and deployed 865402c—let me know what you think. (You'll need to refresh the page to clear the cached JavaScript.) You can also build the URL manually without specifying every setting, like https://randompokemon.com?n=1.

**Comment by mid-kid** [comment]
It's perfect. Thanks!

**Comment by nerdydrew** [comment]
I just added a bonus feature. If you include `generate` as a URL parameter (no need for a value), it generates on page load. For example, https://randompokemon.com?n=1&generate would generate one Pokémon automatically.
